workflows:
  android:
    scripts:
      - name: Build Android APK
        working_directory: android
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/**/*.apk
  my-workflow:
    instance_type: mac_pro
    environment:
      java: 19
      xcode: 14.1
      cocoapods: 1.11.3
